on:
  push:
  pull_request:
name: CI
jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        id: checkout
      - name: Setup dependencies
        run: |
          ./setup.sh
          ./xp3.sh lib/GRAB-SAXON.xpl
          ./xp3.sh lib/GRAB-SCHXSLT.xpl
        id: setup
      - name: Run smoketests
        run: |
          ./xp3.sh smoketest/POWER-UP.xpl
          ./xp3.sh smoketest/SMOKETEST-XSLT.xpl
          ./xp3.sh smoketest/SMOKETEST-SCHEMATRON.xpl
        id: exec_smoketests
